#!/bin/bash

set -e

# Stuff for Systemd
APP_NAME="datalogger"
PYTHON_SCRIPT="/home/$USER/VF_Data_Logger/main.py"
VENV="/home/$USER/projects/VF_Data_Logger/.venv/bin/python"
SERVICE_FILE="/etc/systemd/system/${APP_NAME}.service"

# End of

UPLOAD_DIR="/srv/ftp/upload"
INTERFACE="${1:-enp3s0}"
STATIC_IP="192.168.1.150/24"
GATEWAY="192.168.1.1"
DNS="1.1.1.1"
NETWORK_FILE="/etc/systemd/network/20-wired.network"

# Auto-detect first non-loopback Ethernet interface
INTERFACE=$(ip -o link show | awk -F': ' '!/lo|vir|wl/ {print $2; exit}')

if [[ -z "$INTERFACE" ]]; then
    echo "❌ Could not detect a valid Ethernet interface."
    #exit 1
fi

echo "[*] Detected network interface: $INTERFACE"

echo "[*] Installing vsftpd..."

# Detect package manager
if command -v dnf &> /dev/null; then
    sudo dnf install -y vsftpd python3 python3-pip
elif command -v apt &> /dev/null; then
    sudo apt update && sudo apt install -y vsftpd python3 python3-pip
else
    echo "Unsupported package manager. Install vsftpd manually."
    exit 1
fi

echo "[*] Creating upload directory..."
sudo mkdir -p "$UPLOAD_DIR"
sudo chmod 777 "$UPLOAD_DIR"
sudo chown ftp:ftp "$UPLOAD_DIR"

sudo mkdir -p /var/run/vsftpd/empty
sudo chown root:root /var/run/vsftpd/empty
sudo chmod 755 /var/run/vsftpd/empty

echo "[*] Locating vsftpd.conf..."
if [[ -f /etc/vsftpd.conf ]]; then
    CONF_PATH="/etc/vsftpd.conf"
elif [[ -f /etc/vsftpd/vsftpd.conf ]]; then
    CONF_PATH="/etc/vsftpd/vsftpd.conf"
else
    echo "❌ Cannot find vsftpd.conf!"
    exit 1
fi

echo "[*] Backing up original vsftpd.conf..."
sudo cp "$CONF_PATH" "$CONF_PATH.bak"

echo "[*] Writing new vsftpd.conf..."
cat <<EOF | sudo tee "$CONF_PATH" > /dev/null
# This file is automatically generated by the VF_Data_Logger program. 
# See vsftpd.conf.bak for the original
#
listen=NO
listen_ipv6=YES
anonymous_enable=YES
local_umask=002
anon_upload_enable=YES
anon_mkdir_write_enable=YES
dirmessage_enable=YES
use_localtime=YES
xferlog_enable=YES
connect_from_port_20=NO
xferlog_file=/var/log/vsftpd.log
secure_chroot_dir=/var/run/vsftpd/empty
pam_service_name=vsftpd
anon_other_write_enable=YES
log_ftp_protocol=YES
ftp_username=ftp
anon_root=/srv/ftp
anon_umask=002
file_open_mode=0664
write_enable=YES

EOF

echo "[*] Opening FTP port in firewall (if applicable)..."
if command -v firewall-cmd &> /dev/null; then
    sudo firewall-cmd --permanent --add-service=ftp
    sudo firewall-cmd --reload
fi

echo "[*] Checking if SELinux exists..."

# Check if SELinux is installed
if ! command -v getenforce &> /dev/null; then
    echo "SELinux is not installed."
else
    echo "SELinux is installed. Configuring..."
sudo setsebool -P allow_ftpd_anon_write=1
sudo semanage fcontext -a -t public_content_rw_t "($UPLOAD_DIR)(/.*)?"
sudo restorecon -Rv $UPLOAD_DIR
fi


echo "[*] Restarting vsftpd..."
sudo systemctl restart vsftpd
sudo systemctl enable vsftpd

python3 -m venv .venv
.venv/bin/pip install -r requirements.txt

echo ""
echo "✅ FTP server is running."
echo "📂 Anonymous uploads are allowed at: ftp://<your-ip-address>/upload/"
echo "   (Replace <your-ip-address> with the IP of this machine.)"


echo "Creating systemd service file..."

sudo tee $SERVICE_FILE > /dev/null <<EOF
[Unit]
Description=VF Data Logger GUI
After=network.target

[Service]
Type=simple
ExecStart=$VENV $PYTHON_SCRIPT
WorkingDirectory=$(dirname "$PYTHON_SCRIPT")
Restart=on-failure
User=$USER
Environment=DISPLAY=:0
Environment=XAUTHORITY=/home/$USER/.Xauthority

[Install]
WantedBy=graphical.target
EOF

echo "Reloading systemd..."
sudo systemctl daemon-reload

echo "Enabling service to start on boot..."
sudo systemctl enable $APP_NAME.service

echo "You can start it now with:"
echo "  sudo systemctl start $APP_NAME.service"
